name: "books"

########################### THIS COMPOSE FILE
# This compose file contains book-related apps
# - Calibre
# - Calibre-web
# - Readarr

### ANCHORS
# - The following achors serve as my baseline info that is included in most of my containers
# - Default behaviour is to include all entries below '&home-lab-default' by adding <<: *homelab-default to each container 
# - To add additional env args and labels to a container, I can still use the defaults with <<: &env and <<: &labels, then add additional entries 

x-app: &homelab-default 
  restart: unless-stopped
  security_opt:
    - apparmor:unconfined
  networks:
    - homelab
  environment: &env
    PUID: ${PUID}
    PGID: ${PGID}
    TZ: ${TZ}
    TP_THEME: organizr
  labels: &labels
    com.centurylinklabs.watchtower.enable: "true"

### SERVICES
services:

  ## BOOKS 
  calibre:
    #description: book library, used mainly for auto-import and conversion
    <<: *homelab-default
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    volumes:
      - ${MEDIADIR}/media/books:/config
      - ${MEDIADIR}/media/books/uploads:/uploads 
      - ${MEDIADIR}/media/books/plugins:/plugins
    ports:
      - 8086:8080
      - 8087:8081
      - 9090:9090
  
  calibre-web:
    #descrtion: webUI for library and host for kobo-sync
    <<: *homelab-default
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      DOCKER_MODS: linuxserver/mods:universal-calibre
    volumes:
      - ${DOCKERDIR}/appdata/calibre-web:/config
      - ${MEDIADIR}/media/books:/books
    depends_on:
      - calibre
    ports:
      - 8083:8083
  
  readarr:
    #description: book organizer and downloader
    <<: *homelab-default
    image: ghcr.io/hotio/readarr
    container_name: readarr
    volumes:
      - ${DOCKERDIR}/appdata/readarr:/config
      - ${MEDIADIR}/media/books:/books
      - ${MEDIADIR}/torrents/books:/downloads
    ports:
      - 8787:8787

### NETWORKS
networks:
  homelab:
    driver: bridge
    external: true