name: "media"

########################### THIS COMPOSE FILE
# This compose file contains the arrs and media management apps
# - Overseer
# - Prowlarr
# - qBittorrent
# - Radarr/Radarr4k
# - Recyclarr
# - Sonarr/Sonarr4k
# - Stash
# - Tautulli
# - Unpackerr
# - Watcharr

### ANCHORS
# - The following achors serve as my baseline info that is included in most of my containers
# - Default behaviour is to include all entries below '&home-lab-default' by adding <<: *homelab-default to each container 
# - To add additional env args and labels to a container, I can still use the defaults with <<: &env and <<: &labels, then add additional entries 

x-app: &homelab-default 
  restart: unless-stopped
  security_opt:
    - no-new-privileges=true
  networks:
    - homelab
  environment: &env
    PUID: ${PUID}
    PGID: ${PGID}
    TZ: ${TZ}
    TP_THEME: organizr
  labels: &labels
    com.centurylinklabs.watchtower.enable: "true"

### SERVICES
services:

  jellyseerr:
    #description: https://github.com/fallenbagel/jellyseerr
    <<: *homelab-default
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    volumes:
      - ${DOCKERDIR}/appdata/jellyseerr:/app/config
    ports:
      - 5056:5055

  overseerr:
    #description: webui for media requests
    <<: *homelab-default
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    volumes:
      - ${DOCKERDIR}/appdata/overseerr:/config
    ports:
      - 5055:5055

  plextraktsync:
    #description: https://github.com/linuxserver-labs/docker-plextraktsync
    <<: *homelab-default
    image: lscr.io/linuxserver-labs/plextraktsync:latest
    container_name: plextraktsync
    volumes:
      - ${DOCKERDIR}/appdata/plextraktsync/config:/config

  prowlarr:
    #description: manage indexers for arr suite
    <<: *homelab-default
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    volumes:
      - ${DOCKERDIR}/appdata/prowlarr:/config
    ports:
      - 9696:9696
  
  qbittorrent:
    #description: torrent client with VPN support
    <<: *homelab-default
    image: ghcr.io/hotio/qbittorrent
    container_name: qbittorrent
    environment:
      <<: *env
      VPN_ENABLED: "true"
      VPN_LAN_NETWORK: 192.168.68.0/22
      VPN_CONF: wg0
      PRIVOXY_ENABLED: "false"
      TP_HOTIO: "true"
    volumes:
      - ${DOCKERDIR}/appdata/qbittorrent:/config
      - ${MEDIADIR}:/media
      - ${STASHDIR}:/stash
      - ${DOCKERDIR}/appdata/themepark/98-themepark-qbittorrent:/etc/cont-init.d/98-themepark/ #this must be manually added, see download script
    ports:
      - 8080:8080
      - 8118:8118
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    dns:
      - 1.1.1.1
  
  radarr: &radarr #I defined radarr here, so when I use radarr4k, I can avoid repeating
    #description: organizer and downloader for movies
    <<: *homelab-default
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - ${DOCKERDIR}/appdata/radarr:/config
      - ${MEDIADIR}:/media
    ports:
      - 7878:7878
    environment: &radarrenv
      <<: *env
      DOCKER_MODS: "ghcr.io/themepark-dev/theme.park:radarr"
  
  radarr4k:
    <<: *radarr
    container_name: radarr4k
    volumes:
      - ${DOCKERDIR}/appdata/radarr4k:/config
      - ${MEDIADIR}:/media
    ports:
      - 7879:7878
    environment:
      <<: *radarrenv
      TP_ADDON: radarr-4k-logo

  recyclarr:
    #description: sync, TRaSH guide quality profiles; https://recyclarr.dev/
    <<: *homelab-default
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr
    volumes:
      - ${DOCKERDIR}/appdata/recyclarr/config:/config

  sonarr: &sonarr 
    #description: organizer and downloader for TV shows
    <<: *homelab-default
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - ${DOCKERDIR}/appdata/sonarr:/config
      - ${MEDIADIR}:/media
    ports:
      - 8989:8989
    environment: &sonarrenv
      <<: *env
      DOCKER_MODS: "ghcr.io/themepark-dev/theme.park:sonarr"
  
  sonarr4k:
    <<: *sonarr
    container_name: sonarr4k
    volumes:
      - ${DOCKERDIR}/appdata/sonarr4k:/config
      - ${MEDIADIR}:/media
    ports:
      - 8990:8989
    environment: 
      <<: *sonarrenv
      TP_ADDON: sonarr-4k-logo
  
  stash:
    <<: *homelab-default
    #description: adult media organizer
    image: stashapp/stash:latest
    container_name: stash
    ports:
      - 9999:9999
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      <<: *env
      STASH_STASH: "/data/"
      STASH_GENERATED: "/generated/"
      STASH_METADATA: "/metadata/"
      STASH_CACHE: "/cache/"
      STASH_PORT: "9999"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDIR}/appdata/stash/config:/root/.stash
      - ${STASHDIR}/media:/data
      - ${STASHDIR}/metadata:/metadata
      - ${STASHDIR}/cache:/cache
      - ${STASHDIR}/blobs:/blobs
      - ${STASHDIR}/generated:/generated
  
  tautullli:
    #descriptoin: stats and mangement for plex
    <<: *homelab-default
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    volumes:
      - ${DOCKERDIR}/appdata/tautulli:/config
    ports:
      - 8181:8181
  
  unpackerr:
    #description: automatically unpack zipped or rarred torrents
    <<: *homelab-default
    image: golift/unpackerr
    container_name: unpackerr
    volumes:
      - ${MEDIADIR}:/media
    env_file:
      - ./.unpackerr.env
  
  watcharr:
    #description: track and rate shows and tv to-watch
    <<: *homelab-default
    image: ghcr.io/sbondco/watcharr:latest
    container_name: watcharr
    ports:
      - 3080:3080
    volumes:
      - ${DOCKERDIR}/appdata/watcharr:/data

#### NETWORKS
networks:
  homelab:
    driver: bridge
    external: true
