version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:main
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /opt/appdata/homepage/config:/app/config # Make sure your local config directory exists
    env_file:
      - /opt/appdata/homepage/.secrets.env
      - /opt/appdata/.id.env
      - /opt/appdata/.timezone.env
    networks:
      - homelab
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined

networks:
  homelab:
    driver: bridge
    external: true
