---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- Glances:
    - Proxmox:    
        widget:
            type: glances
            url: http://{{HOMEPAGE_VAR_PROXMOX_IP}}:61208
            username: {{HOMEPAGE_VAR_GLANCES_USER}}
            password: {{HOMEPAGE_VAR_GLANCES_PASS}}
            metric: info
            chart: false
#    - CPU:    
#        widget:
#            type: glances
#            url: http://{{HOMEPAGE_VAR_PROXMOX_IP}}:61208
#            username: {{HOMEPAGE_VAR_GLANCES_USER}}
#            password: {{HOMEPAGE_VAR_GLANCES_PASS}}
#            metric: cpu
#            chart: false
#    - Memory: 
#        widget:
#            type: glances
#            url: http://{{HOMEPAGE_VAR_PROXMOX_IP}}:61208
#            username: {{HOMEPAGE_VAR_GLANCES_USER}}
#            password: {{HOMEPAGE_VAR_GLANCES_PASS}}
#            metric: memory
#            chart: false
    - Temperature:
        widget:
            type: glances
            url: http://{{HOMEPAGE_VAR_PROXMOX_IP}}:61208
            username: {{HOMEPAGE_VAR_GLANCES_USER}}
            password: {{HOMEPAGE_VAR_GLANCES_PASS}}
            metric: sensor:Package id 0
            chart: false
    - NAS:
        href: http://{{HOMEPAGE_VAR_OMV_IP}}
        widget:
            type: glances
            url: http://{{HOMEPAGE_VAR_PROXMOX_IP}}:61208
            username: {{HOMEPAGE_VAR_GLANCES_USER}}
            password: {{HOMEPAGE_VAR_GLANCES_PASS}}
            metric: fs:/mnt/pve/vdisk-nas
            chart: false
    - Backup:
        widget:
            type: glances
            url: http://{{HOMEPAGE_VAR_PROXMOX_IP}}:61208
            username: {{HOMEPAGE_VAR_GLANCES_USER}}
            password: {{HOMEPAGE_VAR_GLANCES_PASS}}
            metric: fs:/mnt/backups
            chart: false

- Media:
    - Overseerr:
        icon: overseerr.png
        href: https://overseerr.{{HOMEPAGE_VAR_DOMAIN}}
#        description: request shows and movies
        server: my-docker
        container: overseerr 
        widget:
            type: overseerr
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:5055
            key: {{HOMEPAGE_VAR_OVERSEER_KEY}}
    - Tautulli:
        icon: tautulli.png
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:8181
#        description: Monitor Plex streaming
        server: my-docker
        container: tautulli
        widget:
            type: tautulli
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:8181
            key: {{HOMEPAGE_VAR_TAUTULLI_KEY}}
    - Plex:
        icon: plex.png
        href: http://{{HOMEPAGE_VAR_PLEX_IP}}:32400/web
#        description: Plex server
        widget:
            type: plex
            url: http://{{HOMEPAGE_VAR_PLEX_IP}}:32400
            key: {{HOMEPAGE_VAR_PLEX_KEY}}
            fields: ["streams", "movies", "tv"]

- Libraries:
    - Mealie:
        icon: mealie.png
        href: https://mealie.{{HOMEPAGE_VAR_DOMAIN}}
#        description: my recipes
        server: my-docker
        container: mealie
        widget:
            type: mealie
            url: https://mealie.{{HOMEPAGE_VAR_DOMAIN}}
            key: {{HOMEPAGE_VAR_MEALIE_KEY}}
    - Kavita:
        icon: kavita.png
        href: https://kavita.{{HOMEPAGE_VAR_DOMAIN}}
#        description: manga and comic library
        server: my-docker
        container: kavita
        widget:
            type: kavita
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:5000
            username: {{HOMEPAGE_VAR_USER}}
            password: {{HOMEPAGE_VAR_KAVITA_PASS}}
    - Calibre-web:
        icon: calibre.png
        href: https://calibreweb.{{HOMEPAGE_VAR_DOMAIN}}
#        description: book library
        server: my-docker
        container: calibre-web
        widget:
            type: calibreweb
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:8083
            username: {{HOMEPAGE_VAR_USER}}
            password: {{HOMEPAGE_VAR_CALIBRE_PASS}}

- Movies:
    - Radarr:
        icon: radarr.png
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:7878
#        description: manage movies
        server: my-docker
        container: radarr
        widget:
            type: radarr
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:7878
            key: {{HOMEPAGE_VAR_RADARR_KEY}}
    - Radarr 4K:
        icon: radarr-light.png
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:7879
#        description: manage movies (4k)
        server: my-docker
        container: radarr4k
        widget:
            type: radarr
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:7879
            key: {{HOMEPAGE_VAR_RADARR_4K_KEY}}

- TV:
    - Sonarr:
        icon: sonarr.png
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:8989
#        description: manage TV shows
        server: my-docker
        container: sonarr
        widget:
            type: sonarr
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:8989
            key: {{HOMEPAGE_VAR_SONARR_KEY}}
            enableQueue: true
    - Sonarr 4k:
        icon: sonarr.png
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:8990
#        description: manage TV show (4k)
        server: my-docker
        container: sonarr4k
        widget:
            type: sonarr
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:8990
            key: {{HOMEPAGE_VAR_SONARR_4K_KEY}}
            enableQueue: true

- Reading:
    - Kaizoku:
        icon: kaizoku.png
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:8089
#        description: manage manga
        server: my-docker
        container: kaizoku
    - Kapowarr:
        icon: https://casvt.github.io/Kapowarr/assets/img/favicon.svg
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:5656
#        description: manage comics
        server: my-docker
        container: kapowarr
    - Mobilism:
          href: https://forum.mobilism.org/index.php
          icon: https://d1nxzqpcg2bym0.cloudfront.net/google_play/com.mobilismmarket.appmarket/1a41d6f2-3f2a-11e8-a372-4ba5557b983c/128x128
    - Z-lib:
          href: https://{{HOMEPAGE_VAR_ZLIB_B}}
          icon: https://zlibrary-ca.se/favicon.svg

- Downloads:
    - qBittorrent:
        icon: qbittorrent.png
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:8080
#        description: manage downloads
        server: my-docker
        container: qbittorrent        
        widget:
            type: qbittorrent
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:8080
            username: {{HOMEPAGE_VAR_QB_USER}}
            password: {{HOMEPAGE_VAR_QB_PASS}}
    - Prowlarr:
        icon: prowlarr.png
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:9696
#        description: Manage indexers for the Arr services
        server: my-docker
        container: prowlarr        
        widget:
            type: prowlarr
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:9696
            key: {{HOMEPAGE_VAR_PROWLARR_KEY}}
            fields: ["numberOfGrabs", "numberOfQueries", "numberOfFailGrabs"]

- Server:
    - Proxmox:
        icon: proxmox.png
        href: https://proxmox.{{HOMEPAGE_VAR_DOMAIN}}
#        description: my homelab
        widget:
            type: proxmox
            url: https://{{HOMEPAGE_VAR_PROXMOX_IP}}:8006
            username: {{HOMEPAGE_VAR_PROXMOX_USER}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASS}}
    - NPM:
        icon: nginx-proxy-manager.png
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:81
        server: my-docker 
        container: npm
#        description: reverse proxy
        widget:
            type: npm
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:81
            username: {{HOMEPAGE_VAR_USER_EMAIL}}
            password: {{HOMEPAGE_VAR_NPM_PASS}}
    - Authentik:
        icon: authentik.png
        href: https://auth.{{HOMEPAGE_VAR_DOMAIN}}
        server: my-docker
        container: authentik-server
#        description: user control
        widget:
            type: authentik
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:9000
            key: {{HOMEPAGE_VAR_AUTH_KEY}}

- Docker:
    - Portainer:
        icon: portainer.png
        href: https://portainer.{{HOMEPAGE_VAR_DOMAIN}}
#        description: Manage docker containers                         
        server: my-docker
        container: portainer
        widget:
            type: portainer
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:9001
            env: 2
            key: {{HOMEPAGE_VAR_PORTAINER_KEY}}

- Watchtower:
    - Watchtower (Docker):
        icon: watchtower.png
#        description: automatic docker image updates for main 
        server: my-docker
        container: watchtower
    - Watchtower (Bots):
        icon: watchtower.png
#        description: automatic docker image updates for bots
        server: docker-bots
        container: watchtower

- Cleanup:
    - Docker-gc (Docker):
        icon: docker-gc.png
#        description: automatic docker cleanup for main 
        server: my-docker
        container: docker-gc
    - Docker-gc (Bots):
        icon: docker-gc.png
#        description: automatic docker cleanup for bots
        server: docker-bots
        container: docker-gc

- Home:
    - Home Assistant:
        icon: home-assistant.png
        href: https://hass.{{HOMEPAGE_VAR_DOMAIN}}
#        description: manage my smarthome
        widget:
            type: homeassistant
            url: http://{{HOMEPAGE_VAR_HASS_IP}}:8123
            key: {{HOMEPAGE_VAR_HASS_KEY}}
            custom:
              - state: climate.my_ecobee
                label: Furnace
              - state: sensor.my_ecobee_temperature
                label: Temp
#              - state: cover.garage_door
#                label: Garage
#              - template: "{{ states.switch|selectattr('state','equalto','on')|list|length }}"
#                label: Switches 
              - template: "{{ state_attr('weather.forecast_home_assistant','forecast')[0].templow | int(1) }}/{{ state_attr('weather.forecast_home_assistant','forecast')[1].temperature | int(1) }} °C"
                label: Tomorrow

    - Homebridge:
        icon: homebridge.png
        href: http://{{HOMEPAGE_VAR_HOMEBRIDGE_IP}}:8581
#        description: manage Homekit
        widget:
            type: homebridge
            url: http://{{HOMEPAGE_VAR_HOMEBRIDGE_IP}}:8581
            username: {{HOMEPAGE_VAR_USER}}
            password: {{HOMEPAGE_VAR_HOMEBRIDGE_PASS}}
#    - Forecast:
#        icon: rsshub.png
#        href: https://hass.{{HOMEPAGE_VAR_DOMAIN}}
#        widget:
#          type: homeassistant
#          url: http://{{HOMEPAGE_VAR_HASS_IP}}:8123
#          key: {{HOMEPAGE_VAR_HASS_KEY}}
#          custom:
#            - template: "{{ state_attr('weather.forecast_home_assistant','forecast')[0].templow | int(1) }}/{{ state_attr('weather.forecast_home_assistant','forecast')[0].temperature | int(1) }} °C"
#              label: Today
#            - template: "{{ state_attr('weather.forecast_home_assistant','forecast')[0].templow | int(1) }}/{{ state_attr('weather.forecast_home_assistant','forecast')[1].temperature | int(1) }} °C"
#              label: Tomorrow

- Pi-Hole:
    - Cloudblock Pi (Primary DNS):
        icon: pi-hole.png
        href: https://{{HOMEPAGE_VAR_PI_IP}}3/admin
#        description: Primary Cloudblock on Raspberry Pi
        server: docker-cloudblock
        container: pihole
        widget:
            type: pihole
            url: https://{{HOMEPAGE_VAR_PI_IP}}3
            key: {{HOMEPAGE_VAR_PI_KEY}}
    - Pi-Hole (Secondary DNS):
        icon: pi-hole.png
        href: http://{{HOMEPAGE_VAR_PI_IP}}2/admin
#        description: Secondary Pi-Hole on Proxmox
        widget:
            type: pihole
            url: http://{{HOMEPAGE_VAR_PI_IP}}2
            key: {{HOMEPAGE_VAR_PI_KEY}}

- Bots:
    - Microsoft Rewards Farmer:
        icon: bing.png
        href: http://{{HOMEPAGE_VAR_BOT_IP}}:50947
        description: Farm Microsoft Rewards points
        server: docker-bots
        container: msrf
    - ArchiSteamFarm:
        icon: archisteamfarm.png
        href: http://{{HOMEPAGE_VAR_BOT_IP}}:1242
        description: Steam card farmer, and free game collector
        server: docker-bots
        container: asf
    - Epic Games:
        icon: https://cdn2.unrealengine.com/eg-shield-logo-white-f8185c103d8d.svg
        description: Claims free games on Epic
        server: docker-bots
        container: epicgames-freegames
    - Free Games Claimer:
        icon: twitch.png
        href: http://{{HOMEPAGE_VAR_BOT_IP}}:6080
        description: Claims free games on GOG, Prime
        server: docker-bots
        container: fgc
    - Tracker Auto Login:
        icon: https://www.torrentleech.org/favicon.ico
        href: https://torrentleech.org
        description: daily automatic login
        server: docker-bots
        container: trackerautologin

- Game Servers:
    - Minecraft Server - Creative:
        icon: minecraft.png
        href: https://crafty.{{HOMEPAGE_VAR_DOMAIN}}:8443
#        description: Ubuntu server on Oracle
        widget:
            type: gamedig
            serverType: minecraftbe
            url: udp://{{HOMEPAGE_VAR_ORACLE_IP}}:19132
            fields: ["name", "players", "status"]
    - Minecraft Server - Survival:
        icon: minecraft.png
        href: https://crafty.{{HOMEPAGE_VAR_DOMAIN}}:8443
#        description: Ubuntu server on Oracle
        widget:
            type: gamedig
            serverType: minecraftbe
            url: udp://{{HOMEPAGE_VAR_ORACLE_IP}}:19134
            fields: ["name", "players", "status"]