---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- Libraries:
    
    - Plex:
        icon: plex.png
        href: http://{{HOMEPAGE_VAR_PLEX_IP}}:32400/web
        description: Plex server
        widget:
            type: plex
            url: http://{{HOMEPAGE_VAR_PLEX_IP}}:32400
            key: {{HOMEPAGE_VAR_PLEX_KEY}}
            fields: ["streams", "movies", "tv"]

    - Mealie:
        icon: mealie.png
        href: https://mealie.{{HOMEPAGE_VAR_DOMAIN}}
        description: my recipes
        server: my-docker
        container: mealie
        widget:
            type: mealie
            url: https://mealie.{{HOMEPAGE_VAR_DOMAIN}}
            key: {{HOMEPAGE_VAR_MEALIE_KEY}}

    - Kavita:
        icon: kavita.png
        href: https://kavita.{{HOMEPAGE_VAR_DOMAIN}}
        description: manga and comic library
        server: my-docker
        container: kavita
        widget:
            type: kavita
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:5000
            username: {{HOMEPAGE_VAR_USER}}
            password: {{HOMEPAGE_VAR_KAVITA_PASS}}

    - Calibre-web:
        icon: calibre.png
        href: https://calibreweb.{{HOMEPAGE_VAR_DOMAIN}}
        description: book library
        server: my-docker
        container: calibre-web
        widget:
            type: calibreweb
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:8083
            username: {{HOMEPAGE_VAR_USER}}
            password: {{HOMEPAGE_VAR_CALIBRE_PASS}}

- Media Management:
    
    - Tautulli:
        icon: tautulli.png
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:8181
        description: Monitor Plex streaming
        server: my-docker
        container: tautulli
        widget:
            type: tautulli
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:8181
            key: {{HOMEPAGE_VAR_TAUTULLI_KEY}}

    - Overseerr:
        icon: overseerr.png
        href: https://overseerr.{{HOMEPAGE_VAR_DOMAIN}}
        description: request shows and movies
        server: my-docker
        container: overseerr 
        widget:
            type: overseerr
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:5055
            key: {{HOMEPAGE_VAR_OVERSEER_KEY}}
            
    - Radarr:
        icon: radarr.png
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:7878
        description: manage movies
        server: my-docker
        container: radarr
        widget:
            type: radarr
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:7878
            key: {{HOMEPAGE_VAR_RADARR_KEY}}

    - Radarr 4K:
        icon: radarr-light.png
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:7879
        description: manage movies (4k)
        server: my-docker
        container: radarr4k
        widget:
            type: radarr
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:7879
            key: {{HOMEPAGE_VAR_RADARR_4K_KEY}}

    - Sonarr:
        icon: sonarr.png
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:8989
        description: manage TV shows
        server: my-docker
        container: sonarr
        widget:
            type: sonarr
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:8989
            key: {{HOMEPAGE_VAR_SONARR_KEY}}
            enableQueue: true

    - Sonarr 4k:
        icon: sonarr.png
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:8990
        description: manage TV show (4k)
        server: my-docker
        container: sonarr4k
        widget:
            type: sonarr
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:8990
            key: {{HOMEPAGE_VAR_SONARR_4K_KEY}}
            enableQueue: true

    - Kaizoku:
        icon: kaizoku.png
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:8089
        description: manage manga
        server: my-docker
        container: kaizoku

    - Kapowarr:
        icon: https://play-lh.googleusercontent.com/wu4oAwczFeXlLVgUd6Mp3fYoxn1Cf0alB_2-5h9dnUL9-8DllwVdFL2BbizIZDDNGBA=w480-h960
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:5656
        description: manage comics
        server: my-docker
        container: kapowarr

- Networking:
    
    - qBittorrent:
        icon: qbittorrent.png
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:8080
        description: manage downloads
        server: my-docker
        container: qbittorrent        
        widget:
            type: qbittorrent
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:8080
            username: {{HOMEPAGE_VAR_QB_USER}}
            password: {{HOMEPAGE_VAR_QB_PASS}}
    
    - Prowlarr:
        icon: prowlarr.png
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:9696
        description: Manage indexers for the Arr services
        server: my-docker
        container: prowlarr        
        widget:
            type: prowlarr
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:9696
            key: {{HOMEPAGE_VAR_PROWLARR_KEY}}
        
    - NPM:
        icon: nginx-proxy-manager.png
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:81
        server: my-docker 
        container: npm
        description: reverse proxy
        widget:
            type: npm
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:81
            username: {{HOMEPAGE_VAR_USER_EMAIL}}
            password: {{HOMEPAGE_VAR_NPM_PASS}}

    - Authentik:
        icon: authentik.png
        href: https://auth.{{HOMEPAGE_VAR_DOMAIN}}
        server: my-docker
        container: authentik-server
        description: user control
        widget:
            type: authentik
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:9000
            key: {{HOMEPAGE_VAR_AUTH_KEY}}

- Home:
    
    - Home Assistant:
        icon: home-assistant.png
        href: https://hass.{{HOMEPAGE_VAR_DOMAIN}}
        description: manage my smarthome
        widget:
            type: homeassistant
            url: http://{{HOMEPAGE_VAR_HASS_IP}}:8123
            key: {{HOMEPAGE_VAR_HASS_KEY}}
            custom:
              - state: climate.my_ecobee
                label: Furnace
              - state: sensor.my_ecobee_temperature
                label: Temp
              - state: cover.garage_door
                label: Garage
              - template: "{{ states.switch|selectattr('state','equalto','on')|list|length }}"
                label: Switches 

    - Cloudblock (Primary DNS):
        icon: pi-hole.png
        href: https://{{HOMEPAGE_VAR_PI_IP}}3/admin
        description: Primary Cloudblock on Raspberry Pi
        server: docker-cloudblock
        container: pihole
        widget:
            type: pihole
            url: https://{{HOMEPAGE_VAR_PI_IP}}3
            key: {{HOMEPAGE_VAR_PI_KEY}}

    - Pi-Hole (Secondary DNS):
        icon: pi-hole.png
        href: http://{{HOMEPAGE_VAR_PI_IP}}2/admin
        description: Secondary Pi-Hole on Proxmox
        widget:
            type: pihole
            url: http://{{HOMEPAGE_VAR_PI_IP}}2
            key: {{HOMEPAGE_VAR_PI_KEY}}
    
    - Forecast:
        href: https://hass.{{HOMEPAGE_VAR_DOMAIN}}
        widget:
          type: homeassistant
          url: http://{{HOMEPAGE_VAR_HASS_IP}}:8123
          key: {{HOMEPAGE_VAR_HASS_KEY}}
          custom:
            - template: "{{ state_attr('weather.forecast_home_assistant','forecast')[0].templow | int(1) }}/{{ state_attr('weather.forecast_home_assistant','forecast')[0].temperature | int(1) }} °C"
              label: Today
            - template: "{{ state_attr('weather.forecast_home_assistant','forecast')[0].templow | int(1) }}/{{ state_attr('weather.forecast_home_assistant','forecast')[1].temperature | int(1) }} °C"
              label: Tomorrow

    - Open Media Vault:
        icon: openmediavault.png
        href: http://{{HOMEPAGE_VAR_OMV_IP}}
        description: NAS storage

- Bots:

    - Microsoft Rewards Farmer:
        icon: bing.png
        href: http://{{HOMEPAGE_VAR_BOT_IP}}:50947
        description: Farm Microsoft Rewards points
        server: docker-bots
        container: msrf

    - ArchiSteamFarm:
        icon: archisteamfarm.png
        href: http://{{HOMEPAGE_VAR_BOT_IP}}:1242
        description: Steam card farmer, and free game collector
        server: docker-bots
        container: asf

    - Epic Games:
        icon: https://www.epicgames.com/favicon.ico
        description: Free games checker
        server: docker-bots
        container: epicgames-freegames
            
    - Tracker Auto Login:
        icon: https://www.torrentleech.org/favicon.ico
        href: https://torrentleech.org
        description: daily automatic login
        server: docker-bots
        container: trackerautologin

    - Minecraft Server - Creative:
        icon: minecraft.png
        href: https://crafty.{{HOMEPAGE_VAR_DOMAIN}}:8443
        description: Ubuntu server on Oracle
        widget:
            type: gamedig
            serverType: minecraftbe
            url: udp://{{HOMEPAGE_VAR_ORACLE_IP}}:19132
            fields: ["name", "players", "status"]

    - Minecraft Server - Survival:
        icon: minecraft.png
        href: https://crafty.{{HOMEPAGE_VAR_DOMAIN}}:8443
        description: Ubuntu server on Oracle
        widget:
            type: gamedig
            serverType: minecraftbe
            url: udp://{{HOMEPAGE_VAR_ORACLE_IP}}:19134
            fields: ["name", "players", "status"]

- Server:

    - Proxmox:
        icon: proxmox.png
        href: https://proxmox.{{HOMEPAGE_VAR_DOMAIN}}
        description: my homelab
        widget:
            type: proxmox
            url: https://{{HOMEPAGE_VAR_PROXMOX_IP}}:8006
            username: {{HOMEPAGE_VAR_PROXMOX_USER}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASS}}

    - Portainer:
        icon: portainer.png
        href: https://portainer.{{HOMEPAGE_VAR_DOMAIN}}
        description: Manage docker containers                         
        server: my-docker
        container: portainer
        widget:
            type: portainer
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:9001
            env: 2
            key: {{HOMEPAGE_VAR_PORTAINER_KEY}}
    
    - Watchtower - Docker:
        icon: watchtower.png
        description: automatic docker image updates for main services
        server: my-docker
        container: watchtower

    - Watchtower - Bots:
        icon: watchtower.png
        description: automatic docker image updates for bots
        server: docker-bots
        container: watchtower

    - Docker-gc - Docker:
        icon: docker-gc.png
        description: automatic docker cleanup for main services
        server: my-docker
        container: docker-gc

    - Docker-gc - Bots:
        icon: docker-gc.png
        description: automatic docker cleanup for bots
        server: docker-bots
        container: docker-gc