name: "system"

########################### THIS COMPOSE FILE
# This compose file contains docker and system management utilities
# - Dockerproxy
# - Dockge
# - Portainer
# - PGadmin
# - Uptime-kuma
# - Watchtower

### ANCHORS
# - The following achors serve as my baseline info that is included in most of my containers
# - Default behaviour is to include all entries below '&home-lab-default' by adding <<: *homelab-default to each container 
# - To add additional env args and labels to a container, I can still use the defaults with <<: &env and <<: &labels, then add additional entries 

x-app: &homelab-default 
  restart: unless-stopped
  security_opt:
    - apparmor:unconfined
  networks:
    - homelab
  environment: &env
    PUID: ${PUID}
    PGID: ${PGID}
    TZ: ${TZ}
  labels: &labels
    com.centurylinklabs.watchtower.enable: "true"

### SERVICES
services:

  ### MANAGEMENT
  dockerproxy:
    # description: proxy for docker
    <<: *homelab-default
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    ports:
      - 127.0.0.1:2375:2375
    environment:
      <<: *env
      CONTAINERS: 1 # Allow access to viewing containers
      SERVICES: 1 # Allow access to viewing services (necessary when using Docker Swarm)
      TASKS: 1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      POST: 0 # Disallow any POST operations (effectively read-only)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only

  dockge:
    # description: compose manager/creator
    <<: *homelab-default
    container_name: dockge
    image: louislam/dockge:1
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERDIR}/appdata/dockge/data:/app/data
      - ${DOCKERDIR}/compose:${DOCKERDIR}/compose
    environment:
      <<: *env
      DOCKGE_STACKS_DIR: ${DOCKERDIR}/compose

  pgadmin:
    #description: manage my Authentik Dabase
    <<: *homelab-default
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - 5050:80
    restart: always
    volumes:
      - ${DOCKERDIR}/appdata/pgadmin:/var/lib/pgadmin #requires user to run: sudo chown -R 5050:5050 ${DOCKERDIR}/appdata/pgadmin

  portainer:
    # description: alternate docker manager, this is the BE version (free for 2 nodes, requires sign-up)
    <<: *homelab-default
    image: portainer/portainer-ee:latest
    container_name: portainer
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKERDIR}/appdata/portainer-data:/data
    ports:
      - 9001:9000

  uptime-kuma:
    #description: monitor docker and service uptime
    <<: *homelab-default
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    volumes:
      - ${DOCKERDIR}/appdata/uptime-kuma/data:/app/data
    ports:
      - 3001:3001

  watchtower:
    # description: automatically update containers
    <<: *homelab-default
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      <<: *env
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_LABEL_ENABLE: "true"
      WATCHTOWER_INCLUDE_RESTARTING: "true"
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_SCHEDULE: "0 0 3 * * *"
      WATCHTOWER_TIMEOUT: "30"
      WATCHTOWER_HTTP_API_UPDATE: "true"
      WATCHTOWER_HTTP_API_METRICS: "true"
      WATCHTOWER_HTTP_API_TOKEN: "${TOKEN}"
      WATCHTOWER_HTTP_API_PERIODIC_POLLS: "true"
      WATCHTOWER_NOTIFICATIONS: "shoutrrr"
      WATCHTOWER_NOTIFICATION_SKIP_TITLE: "True"
      WATCHTOWER_NOTIFICATION_URL: "${WATCHTOWER_NTFY_URL}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8090:8080

### NETWORKS
networks:
  homelab:
    driver: bridge
    external: true
