---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

title: homelab

headerStyle: clean

Providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

background: https://images.unsplash.com/photo-1681697390349-ce67ad7014e5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3870&q=80
cardBlur: xl

hideErrors: true

layout:

#putting this up here before I start defining tabs makes glances show up on every page
  Glances:
    style: row
    columns: 4
    header: false

## Tab 1 - Media
  Media:
    style: row
    columns: 3
    tab: Media
#    header: false

  Libraries:
    tab: Media
    style: row
    columns: 3
#    header: false

  Movies:
    tab: Media

  TV:
    tab: Media

  Reading:
    tab: Media

  Downloads:
    tab: Media
    style: row
    columns: 2

## Tab 2 - System
  Server:
    tab: System
    style: row
    columns: 3
  
  Docker:
    tab: System

  Watchtower:
    tab: System

  Cleanup:
    tab: System

  Resources:
    tab: System
    style: row
    columns: 4

## Tab 3 - services
  Bots:
    tab: Services
    style: row
    columns: 3

  Home:
    tab: Services

  Pi-Hole:
    tab: Services
  
  Game Servers:
    tab: Services
  
  Projects:
    tab: Services
    style: row
    columns: 4

## Bookmarks - these show up on every page at the bottom 
  Primary:
    style: row
    columns: 2
    header: false

fiveColumns: False
