name: "apps"

# ===== THIS COMPOSE FILE =====
# Services included:
#   - Code-server
#   - Glance
#   - Homepage
#   - Mealie
#   - Vikunja
#   - Flatnotes
#   - Traktor

# == ANCHORS ==
# These anchors define baseline configuration applied to most containers.
# Default behavior:
#   - Include all entries under '&homelab-default' via <<: *homelab-default
#   - Additional labels can be added per container using <<: *labels

x-app: &homelab-default 
  restart: unless-stopped
  security_opt:
    - no-new-privileges=true
  networks:
    - homelab
  labels: &labels
    com.centurylinklabs.watchtower.enable: "true"
  env_file: &env-files
    - ../envs/global.env
    - ../envs/apps.env

services:

  code-server:
    <<: *homelab-default
    #description: https://docs.linuxserver.io/images/docker-code-server/
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      DEFAULT_WORKSPACE: /appdata #optional
    volumes:
      - ./code-server/config:/config
      - ../:/appdata
      - ../:/compose
    ports:
      - 8443:8443

  glance:
    <<: *homelab-default
    image: glanceapp/glance
    container_name: glance
    volumes:
      - ./glance:/app/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/media/backups:/mnt/media:ro
    env_file:
      - ../envs/global.env
      - ../envs/apps.env
      - ../envs/dashboards.env
    ports:
      - 8088:8080

  homepage:
    # description: my preferred dashboard, available at IP:3000
    <<: *homelab-default
    image: ghcr.io/gethomepage/homepage:main
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./homepage/config:/app/config
      - ./homepage/images:/app/public/images
    env_file:
      - ../envs/global.env
      - ../envs/apps.env
      - ../envs/dashboards.env
            
  mealie:
    <<: *homelab-default
    #description: recipe manager
    image: ghcr.io/mealie-recipes/mealie:nightly
    container_name: mealie
    ports:
      - 9925:9000
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - ./mealie:/app/data
    environment:
      #commented-out values are provided in apps.env
      ALLOW_SIGNUP: "false"
      #BASE_URL: "${MEALIE_URL}"
      MAX_WORKERS: "1"
      WEB_CONCURRENCY: "1"
      #SMTP_HOST: "${SMTP_HOST}"
      #SMTP_PORT: "${SMTP_PORT}"
      SMTP_FROM_NAME: "Mealie"
      SMTP_AUTH_STRATEGY: "TLS"
      #SMTP_FROM_EMAIL: "${SMTP_FROM_EMAIL}"
      #SMTP_USER: "${SMTP_USER}"
      #SMTP_PASSWORD: "${SMTP_PASSWORD}"

  vikunja:
    <<: *homelab-default
    image: vikunja/vikunja
    container_name: vikunja
    environment:
      VIKUNJA_DATABASE_PATH: /db/vikunja.db
    ports:
      - 3456:3456
    volumes:
      - ./vikunja/files:/app/vikunja/files
      - ./vikunja/db:/db
    restart: unless-stopped

    #image: vikunja/vikunja
    #container_name: vikunja
    #environment:
      #commented-out values are in apps.env
      #VIKUNJA_SERVICE_PUBLICURL: ${VIKUNJA_SERVICE_PUBLICURL}
    #  VIKUNJA_DATABASE_HOST: db
      #VIKUNJA_DATABASE_PASSWORD: ${VIKUNJA_DATABASE_PASSWORD}
    #  VIKUNJA_DATABASE_TYPE: mysql
    #  VIKUNJA_DATABASE_USER: vikunja
    #  VIKUNJA_DATABASE_DATABASE: vikunja
      #VIKUNJA_SERVICE_JWTSECRET: ${VIKUNJA_SERVICE_JWTSECRET}
    #  VIKUNJA_SERVICE_ENABLETASKATTACHMENTS: 1
    #  VIKUNJA_SERVICE_ENABLEREGISTRATION: 0
    #  VIKUNJA_SERVICE_ENABLEEMAILREMINDERS: 1
    #  VIKUNJA_SERVICE_TIMEZONE: America/Toronto
    #  VIKUNJA_MAILER_ENABLED: 1
    #  VIKUNJA_MAILER_FORCESSL: 1
      #VIKUNJA_MAILER_HOST: ${VIKUNJA_MAILER_HOST}
      #VIKUNJA_MAILER_PORT: ${VIKUNJA_MAILER_PORT}
      #VIKUNJA_MAILER_USERNAME: ${VIKUNJA_MAILER_USERNAME}
      #VIKUNJA_MAILER_PASSWORD: ${VIKUNJA_MAILER_PASSWORD}
    #  VIKUNJA_LOG_LEVEL: INFO
    #  VIKUNJA_LOG_MAIL: stdout
    #  VIKUNJA_LOG_MAILLEVEL: DEBUG
    #  VIKUNJA_CORS_ENABLE: true
    #ports:
    #  - 3456:3456
    #volumes:
    #  - ./vikunja/files:/app/vikunja/files
    #  - ./vikunja/config.yml:/etc/vikunja/config.yml
    #depends_on:
    #  db:
    #    condition: service_healthy
  #db:
  #  <<: *homelab-default
  #  image: mariadb:10
  #  container_name: vikunja-db
  #  command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #  environment:
  #    #MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #    MYSQL_USER: vikunja
  #    #MYSQL_PASSWORD: ${VIKUNJA_DATABASE_PASSWORD}
  #    MYSQL_DATABASE: vikunja
  #  volumes:
  #    - ./vikunja/db:/var/lib/mysql
  #  labels:
  #    - "com.centurylinklabs.watchtower.enable=false"
  #  healthcheck:
  #      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"]
  #      interval: 2s
  
  flatnotes:
    <<: *homelab-default
    container_name: flatnotes
    image: dullage/flatnotes:latest
    environment:
      FLATNOTES_AUTH_TYPE: "none" #change to totp if tunneling
      #FLATNOTES_USERNAME: "user" #enable password details if tunneling
      #FLATNOTES_PASSWORD: "changeMe!"
      #FLATNOTES_SECRET_KEY: "aLongRandomSeriesOfCharacters"
    volumes:
      - /mnt/media/notes:/data
      # Optional. Allows you to save the search index in a different location: 
      - ./flatnotes/index:/data/.flatnotes
    ports:
      - 8383:8080

  tracktor:
    #description: https://github.com/javedh-dev/tracktor
    <<: *homelab-default
    image: ghcr.io/javedh-dev/tracktor:latest
    container_name: tracktor
    ports:
      - "3333:3000"
    volumes:
      - ./tracktor:/data
    environment:
      NODE_ENV: production
      PUBLIC_DEMO_MODE: false

### NETWORKS
networks:
  homelab:
    driver: bridge
    external: true