name: "apps"

########################### THIS COMPOSE FILE
# This compose file contains my dashboard and useful utilities
# - Code Server
# - Homepage
# - NTFY 
# - Mealie

### ANCHORS
# - The following anchors serve as my baseline info that is included in most of my containers
# - Default behavior is to include all entries below '&home-lab-default' by adding <<: *homelab-default to each container 
# - To add additional env args and labels to a container, I can still use the defaults with <<: &env and <<: &labels, then add additional entries 

x-app: &homelab-default 
  restart: unless-stopped
  security_opt:
    - no-new-privileges=true
  networks:
    - homelab
  environment: &env
    PUID: ${PUID}
    PGID: ${PGID}
    TZ: ${TZ}
    TP_THEME: organizr
  labels: &labels
    com.centurylinklabs.watchtower.enable: "true"

### SERVICES
services:

  code-server:
    <<: *homelab-default
    #description: https://docs.linuxserver.io/images/docker-code-server/
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      <<: *env
      DEFAULT_WORKSPACE: /appdata #optional
    volumes:
      - ${DOCKERDIR}/appdata/code-server/config:/config
      - ${DOCKERDIR}/appdata:/appdata
      - ${DOCKERDIR}/compose:/compose
    ports:
      - 8443:8443

  ## UTILITIES
  #dash:
  #  #description: https://getdashdot.com
  #  <<: *homelab-default
  #  container_name: dashdot    
  #  image: mauricenino/dashdot:latest
  #  privileged: true
  #  ports:
  #    - 3333:3001
  #  volumes:
  #    - /:/mnt/host:ro

  flatnotes:
    <<: *homelab-default
    container_name: flatnotes
    image: dullage/flatnotes:latest
    environment:
      <<: *env
      FLATNOTES_AUTH_TYPE: "none" #change to totp if tunneling
      #FLATNOTES_USERNAME: "user" #enable password details if tunneling
      #FLATNOTES_PASSWORD: "changeMe!"
      #FLATNOTES_SECRET_KEY: "aLongRandomSeriesOfCharacters"
    volumes:
      - ${MEDIADIR}/notes:/data
      # Optional. Allows you to save the search index in a different location: 
      - ${DOCKERDIR}/appdata/flatnotes/index:/data/.flatnotes
    ports:
      - 8383:8080

  glance:
    <<: *homelab-default
    image: glanceapp/glance
    container_name: glance
    env_file:
      - ./.homepage.env
    volumes:
      - ${DOCKERDIR}/appdata/glance:/app/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${MEDIADIR}/backups:/mnt/media:ro
    ports:
      - 8088:8080

  homepage:
    # description: my preferred dashboard, available at IP:3000
    <<: *homelab-default
    image: ghcr.io/gethomepage/homepage:main
    container_name: homepage
    env_file:
      - ./.homepage.env    
    ports:
      - 3000:3000
    volumes:
      - ${DOCKERDIR}/appdata/homepage/config:/app/config
      - ${DOCKERDIR}/appdata/homepage/images:/app/public/images
      
  ntfy:
    #description: notification service used by containers
    <<: *homelab-default
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      <<: *env
      NTFY_UPSTREAM_BASE_URL: https://ntfy.sh
      NTFY_CACHE_FILE: /var/lib/ntfy/cache.db
      NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
      NTFY_AUTH_DEFAULT_ACCESS: deny-all
      NTFY_BEHIND_PROXY: true
      NTFY_ATTACHMENT_CACHE_DIR: /var/lib/ntfy/attachments
      NTFY_ENABLE_LOGIN: true
      NTFY_BASE_URL: ${NTFY_BASE_URL}
      #NTFY_LOG_LEVEL: debug
      #NTFY_VISITOR_REQUEST_LIMIT_EXEMPT_HOSTS: 
    volumes:
      - ${DOCKERDIR}/appdata/ntfy/var/cache/ntfy:/var/cache/ntfy
      - ${DOCKERDIR}/appdata/ntfy/etc/ntfy:/etc/ntfy
      - ${DOCKERDIR}/appdata/ntfy:/var/lib/ntfy
    ports:
      - 8150:80

### NETWORKS
networks:
  homelab:
    driver: bridge
    external: true