name: "tunnels"

########################### THIS COMPOSE FILE
# This compose file contains services that are tunnelled by CloudFlare

### ANCHORS
# - The following anchors serve as my baseline info that is included in most of my containers
# - Default behavior is to include all entries below '&home-lab-default' by adding <<: *homelab-default to each container 
# - To add additional env args and labels to a container, I can still use the defaults with <<: &env and <<: &labels, then add additional entries 

x-app: &tunnels-default 
  restart: unless-stopped
  security_opt:
    - no-new-privileges=true
  networks:
    - tunnels
  environment: &env
    TZ: ${TZ}
  labels: &labels
    com.centurylinklabs.watchtower.enable: "true"

services:

  cloudflared: 
      <<: *tunnels-default
      image: cloudflare/cloudflared 
      container_name: cloudflare-tunnel 
      command: tunnel run 
      environment: 
        - TUNNEL_TOKEN=${TUNNEL_TOKEN}

  linkstack:
    <<: *tunnels-default
    hostname: linkstack
    image: linkstackorg/linkstack:latest
    container_name: linkstack
    environment:
      <<: *env
      SERVER_ADMIN: ${ADMIN_EMAIL}
      HTTP_SERVER_NAME: ${SERVER_NAME}
      HTTPS_SERVER_NAME: ${SERVER_NAME}
      LOG_LEVEL: 'info'
      PHP_MEMORY_LIMIT: '256M'
      UPLOAD_MAX_FILESIZE: '8M'
    volumes:
      - ${DOCKERDIR}/appdata/linkstack:/htdocs
      - ${DOCKERDIR}/appdata/certificates:/etc/ssl/apache2
    ports:
      - 8190:443

  mealie:
    <<: *tunnels-default
    #description: recipe manager
    image: ghcr.io/mealie-recipes/mealie:nightly
    container_name: mealie
    ports:
      - 9925:9000
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - ${DOCKERDIR}/appdata/mealie:/app/data
    environment:
      <<: *env
      ALLOW_SIGNUP: "true"
      BASE_URL: "${MEALIE_URL}"
      MAX_WORKERS: "1"
      WEB_CONCURRENCY: "1"
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_PORT: "${SMTP_PORT}"
      SMTP_FROM_NAME: "Mealie"
      SMTP_AUTH_STRATEGY: "TLS"
      SMTP_FROM_EMAIL: "${SMTP_FROM_EMAIL}"
      SMTP_USER: "${SMTP_USER}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      OIDC_AUTH_ENABLED: "true"
      OIDC_SIGNUP_ENABLED: "true"
      OIDC_CONFIGURATION_URL: "${OIDC_CONFIGURATION_URL}"
      OIDC_CLIENT_ID: "${OIDC_CLIENT_ID}"
      OIDC_CLIENT_SECRET: "${OIDC_CLIENT_SECRET}"
      OIDC_AUTO_REDIRECT: "false"
      OIDC_PROVIDER_NAME: "Authentik"
      OIDC_REMEMBER_ME: "true"
      OIDC_USER_GROUP: "mealie-user"
      OIDC_ADMIN_GROUP: "mealie-admin"

  #vikujna
  vikunja:
    <<: *tunnels-default
    image: vikunja/vikunja
    container_name: vikunja
    environment:
      <<: *env
      VIKUNJA_SERVICE_PUBLICURL: ${VIKUNJA_SERVICE_PUBLICURL}
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: ${VIKUNJA_DATABASE_PASSWORD}
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: ${VIKUNJA_SERVICE_JWTSECRET}
      VIKUNJA_SERVICE_ENABLETASKATTACHMENTS: 1
      VIKUNJA_SERVICE_ENABLEREGISTRATION: 0
      VIKUNJA_SERVICE_ENABLEEMAILREMINDERS: 1
      VIKUNJA_SERVICE_TIMEZONE: America/Toronto
      VIKUNJA_MAILER_ENABLED: 1
      VIKUNJA_MAILER_FORCESSL: 1
      VIKUNJA_MAILER_HOST: ${VIKUNJA_MAILER_HOST}
      VIKUNJA_MAILER_PORT: ${VIKUNJA_MAILER_PORT}
      VIKUNJA_MAILER_USERNAME: ${VIKUNJA_MAILER_USERNAME}
      VIKUNJA_MAILER_PASSWORD: ${VIKUNJA_MAILER_PASSWORD}
      VIKUNJA_LOG_LEVEL: INFO
      VIKUNJA_LOG_MAIL: stdout
      VIKUNJA_LOG_MAILLEVEL: DEBUG
    ports:
      - 3456:3456
    volumes:
      - ${DOCKERDIR}/appdata/vikunja/files:/app/vikunja/files
      - ${DOCKERDIR}/appdata/vikunja/config.yml:/etc/vikunja/config.yml
    depends_on:
      db:
        condition: service_healthy
  db:
    <<: *tunnels-default
    image: mariadb:10
    container_name: vikunja-db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: vikunja
      MYSQL_PASSWORD: ${VIKUNJA_DATABASE_PASSWORD}
      MYSQL_DATABASE: vikunja
    volumes:
      - ${DOCKERDIR}/appdata/vikunja/db:/var/lib/mysql
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    healthcheck:
        test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"]
        interval: 2s
        start_period: 30s

networks:
  tunnels:
    driver: bridge
    external: true