name: "manga"

########################### THIS COMPOSE FILE
# This compose file contains Manga-related apps
# - Suwayomi 
# - flaresolverr (dependency for Suwayomi)

### ANCHORS
# - The following achors serve as my baseline info that is included in most of my containers
# - Default behaviour is to include all entries below '&home-lab-default' by adding <<: *homelab-default to each container 
# - To add additional env args and labels to a container, I can still use the defaults with <<: &env and <<: &labels, then add additional entries 

x-app: &homelab-default 
  restart: unless-stopped
  security_opt:
    - no-new-privileges=true
  networks:
    - homelab
  environment: &env
    PUID: ${PUID}
    PGID: ${PGID}
    TZ: ${TZ}
    TP_THEME: organizr
  labels: &labels
    com.centurylinklabs.watchtower.enable: "true"

### SERVICES
services:

  suwayomi: &suwayomi
    #description: https://github.com/Suwayomi/Suwayomi-Server
    <<: *homelab-default
    image: ghcr.io/suwayomi/tachidesk:preview
    container_name: suwayomi
    environment:
      <<: *env
      FLARESOLVERR_ENABLED: true
      FLARESOLVERR_URL: http://flaresolverr:8191
    volumes:
      - ${MEDIADIR}/media/manga:/home/suwayomi/.local/share/Tachidesk/downloads
      - ${DOCKERDIR}/appdata/suwayomi:/home/suwayomi/.local/share/Tachidesk
    ports:
      - "4567:4567"
    restart: on-failure:3

  suwayomi-kids:
    <<: *suwayomi
    image: ghcr.io/suwayomi/tachidesk:preview
    container_name: suwayomi-kids
    volumes:
      - ${MEDIADIR}/media/manga:/home/suwayomi/.local/share/Tachidesk/downloads
      - ${DOCKERDIR}/appdata/suwayomi-kids:/home/suwayomi/.local/share/Tachidesk
    ports:
      - "5678:4567"

  flaresolverr:
    <<: *homelab-default
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      <<: *env
    ports:
      - "8191:8191"
    restart: unless-stopped

#### NETWORKS
networks:
  homelab:
    driver: bridge
    external: true
